---
- name: add mysql group
  group:
    name: mysql
    system: yes
    state: present

- name: add mysql user
  user:
    name: mysql
    group: mysql
    system: yes
    createhome: no
    home: /var/lib/mysql
    shell: /bin/false
    comment: "MySQL Server"
    state: present

- name: create and own mysql dirs
  file:
    path: "{{ item }}"
    owner: mysql
    group: mysql
    mode: 0750
    state: directory
  with_items:
    - "{{ galera_datadir }}"
    - "{{ galera_logdir }}"

- name: Install Percona XtraDB Cluster server (DEB)
  apt: 
    pkg: "{{ item }}" 
    state: present
  with_items:
    - percona-xtradb-cluster-server-5.7
    - python-mysqldb
    - xinetd
  when: ansible_os_family == 'Debian'

- name: Install Percona XtraDB Cluster server (YUM)
  yum: 
    pkg: "{{ item }}"
    state: present
  with_items:
    - Percona-XtraDB-Cluster-56
    - MySQL-python
    - xinetd
  when: ansible_os_family == 'RedHat'
