---
# check if mtab is there
- name: check if mtab exists
  action: shell test -f /etc/mtab && echo "aqui" || echo "nada" 
  register: mtab_check 

# Create link if not already exists. Upstart for mysql needs this! 
- name: create mtab if not exists 
  action: file src=/proc/mounts dest=/etc/mtab state=link
  when: mtab_check.stdout == "nada"

- name: Install Percona XtraDB Cluster server
  apt: pkg={{ item }} 
       state=present
  with_items:
    - percona-xtradb-cluster-server-5.6
    - python-mysqldb
    - xinetd
    - git
  register: aptget

- name: Stop mysql if apt changed
  service: name=mysql state=stopped
  when: aptget.changed